"use client";
import moment from "moment";
import Head from "next/head";

import Image from "next/image";
import { useParams } from "next/navigation";

import React, { useCallback, useEffect, useState } from "react";
import Web3 from "web3";
import ChartContainer from "../../../components/Chart/ChartContainer";
// import Navbar from "../../../components/Navbar";
import { useData } from "@/context/DataContext";
// import Link from "next/link";
import {
  Paper,
  Box,
  Typography,
  Avatar,
  TextField,
  Button,
  Link,
  Grid,
  Card,
  CardContent,
  CardActions,
  Container,
} from "@mui/material";
import { styled } from "@mui/material/styles";
import { MarketProps } from "@/types";

const StyledPaper = styled(Paper)(({ theme }) => ({
  padding: theme.spacing(2),
  borderRadius: theme.shape.borderRadius,
  border: `1px solid ${theme.palette.divider}`,
  display: "flex",
  flexDirection: "column",
  alignItems: "start",
}));

const StyledBox = styled(Box)(({ theme }) => ({
  width: "100%",
  padding: theme.spacing(1),
  marginTop: theme.spacing(1),
  cursor: "pointer",
  textAlign: "center",
  borderRadius: theme.shape.borderRadius,
  "&:hover": {
    backgroundColor: theme.palette.action.hover,
  },
}));

const StyledTextField = styled(TextField)(({ theme }) => ({
  width: "100%",
  margin: theme.spacing(1, 0),
}));

const DescriptionBox = styled(Box)(({ theme }) => ({
  width: "66%", // equivalent to w-2/3 in Tailwind
  flexDirection: "column",
  [theme.breakpoints.down("sm")]: {
    width: "100%", // full width on small devices
  },
}));

const ResolutionSourceTypography = styled(Typography)(({ theme }) => ({
  marginTop: theme.spacing(2),
  marginBottom: theme.spacing(2),
  paddingTop: theme.spacing(1),
  paddingBottom: theme.spacing(1),
  backgroundColor: theme.palette.grey[100], // equivalent to bg-gray-100 in Tailwind
  borderRadius: theme.shape.borderRadius * 2,
  paddingLeft: theme.spacing(1.5),
}));

const Details = () => {
  const { id } = useParams();

  const { polymarket, account, loadWeb3, loading, polyToken } = useData();
  const [market, setMarket] = useState<MarketProps>();
  const [selected, setSelected] = useState<string>("YES");
  const [dataLoading, setDataLoading] = useState(true);
  const [button, setButton] = useState<string>("Trade");

  const [input, setInput] = useState("");

  const getMarketData = useCallback(async () => {
    var data = await polymarket.methods.questions(id).call({ from: account });
    setMarket({
      id: data.id,
      title: data.question,
      imageHash: data.creatorImageHash,
      totalAmount: data?.totalAmount && parseInt(data?.totalAmount),
      totalYes: data?.totalYesAmount && parseInt(data?.totalYesAmount),
      totalNo: data?.totalNoAmount && parseInt(data?.totalNoAmount),
      description: data?.description && data?.description,
      endTimestamp: data?.endTimestamp && parseInt(data?.endTimestamp),
      resolverUrl: data?.resolverUrl && data?.resolverUrl,
    });
    setDataLoading(false);
  }, [account, id, polymarket]);

  const handleTrade = async () => {
    var bal = await polyToken.methods.balanceOf(account).call();
    setButton("Please wait");

    if (input && selected === "YES") {
      if (parseInt(input) < parseInt(Web3.utils.fromWei(bal, "ether"))) {
        await polyToken.methods
          .approve(polymarket._address, Web3.utils.toWei(input, "ether"))
          .send({ from: account });
        await polymarket.methods
          .addYesBet(id, Web3.utils.toWei(input, "ether"))
          .send({ from: account });
      }
    } else if (input && selected === "NO") {
      if (parseInt(input) < parseInt(Web3.utils.fromWei(bal, "ether"))) {
        await polyToken.methods
          .approve(polymarket._address, Web3.utils.toWei(input, "ether"))
          .send({ from: account });
        await polymarket.methods
          .addNoBet(id, Web3.utils.toWei(input, "ether"))
          .send({ from: account });
      }
    }
    await getMarketData();
    setButton("Trade");
  };

  useEffect(() => {
    loadWeb3().then(() => {
      if (!loading) getMarketData();
    });
  }, [loading]);

  return (
    <div>
      <Head>
        <title>xParametric</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth={"xl"}>
        {dataLoading ? (
          <Box
            display="flex"
            flexDirection="column"
            justifyContent="center"
            alignItems="center"
            height="100%"
            width="100%"
            pt={10}
          >
            <Box textAlign="center">
              <Typography variant="h4" component="div" fontWeight="bold">
                Loading...
              </Typography>
            </Box>
          </Box>
        ) : (
          <Box sx={{ width: "100%", pt: 1 }}>
            <Paper
              sx={{
                p: 3,
                display: "flex",
                alignItems: "flex-start",
                border: 1,
                borderColor: "grey.300",
              }}
            >
              <Box style={{ display: "flex", flexDirection: "row" }}>
                <Avatar
                  src={`https://ipfs.infura.io/ipfs/${market?.imageHash}`}
                  style={{ width: "55px", height: "55px", marginRight: "16px" }}
                  alt="Market"
                />
                <Box
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "start",
                    flex: "1 1 50%",
                  }}
                >
                  <Typography variant="caption" style={{ color: "gray" }}>
                    {"Type"}{" "}
                  </Typography>
                  <Typography variant="h6">{market?.title}</Typography>
                </Box>
              </Box>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "row",
                  alignItems: "center",
                  ml: 1.5,
                }}
              >
                <Paper
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "start",
                    padding: "12px",
                    backgroundColor: "#f5f5f5",
                  }}
                >
                  <Typography variant="caption" style={{ color: "gray" }}>
                    Market End on
                  </Typography>
                  <Typography variant="body1">
                    {market?.endTimestamp
                      ? moment(
                          parseInt(market?.endTimestamp).toFixed(0)
                        ).format("MMMM D, YYYY")
                      : "N/A"}
                  </Typography>
                </Paper>
                <Paper
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "start",
                    padding: "12px",
                    backgroundColor: "#f5f5f5",
                    marginLeft: "16px",
                  }}
                >
                  <Typography variant="caption" style={{ color: "gray" }}>
                    Total Volume
                  </Typography>
                  <Typography variant="body1">
                    {(market?.totalAmount &&
                      Web3.utils.fromWei(
                        market?.totalAmount.toString() ?? "0",
                        "ether"
                      )) ??
                      0}{" "}
                    POLY
                  </Typography>
                </Paper>
              </Box>
            </Paper>
            <Box
              sx={{ display: "flex", flexDirection: "column", gap: 2, mt: 5 }}
            >
              <Grid container spacing={2}>
                <Grid item xs={12} md={8}>
                  <StyledPaper sx={{ width: "100%", height: 400 }}>
                    <ChartContainer questionId={market?.id ?? "0"} />
                  </StyledPaper>
                </Grid>

                <Grid item xs={12} md={4}>
                  <Card variant="outlined" sx={{ maxWidth: 345, mx: "auto" }}>
                    <CardContent>
                      <Typography variant="h6" sx={{ textAlign: "center" }}>
                        Buy
                      </Typography>
                      <hr style={{ width: "100%", margin: "16px 0" }} />
                      <Typography
                        variant="subtitle1"
                        sx={{ textAlign: "center" }}
                      >
                        Pick Outcome
                      </Typography>

                      {/* YES Option */}
                      <Box
                        sx={{
                          backgroundColor:
                            selected === "YES" ? "#4caf50" : "#f5f5f5",
                          color: selected === "YES" ? "#fff" : "inherit",
                          textAlign: "center",
                          py: 1,
                          my: 1,
                          borderRadius: 1,
                          cursor: "pointer",
                        }}
                        onClick={() => setSelected("YES")}
                      >
                        <Typography variant="subtitle2">
                          YES{" "}
                          {market?.totalAmount && market?.totalYes
                            ? (
                                (parseInt(market?.totalYes) * 100) /
                                parseInt(market?.totalAmount)
                              ).toFixed(2)
                            : "0"}
                          %
                        </Typography>
                      </Box>

                      {/* NO Option */}
                      <Box
                        sx={{
                          backgroundColor:
                            selected === "NO" ? "#4caf50" : "#f5f5f5",
                          color: selected === "NO" ? "#fff" : "inherit",
                          textAlign: "center",
                          py: 1,
                          my: 1,
                          borderRadius: 1,
                          cursor: "pointer",
                        }}
                        onClick={() => setSelected("NO")}
                      >
                        <Typography variant="subtitle2">
                          NO{" "}
                          {market?.totalAmount && market?.totalNo
                            ? (
                                (parseInt(market?.totalNo) * 100) /
                                parseInt(market?.totalAmount)
                              ).toFixed(2)
                            : "0"}
                          %
                        </Typography>
                      </Box>

                      <Typography
                        variant="body2"
                        sx={{ mt: 2, textAlign: "center" }}
                      >
                        How much?
                      </Typography>

                      {/* Input Field */}
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                          border: "1px solid #e0e0e0",
                          p: 1,
                          borderRadius: 1,
                          my: 2,
                        }}
                      >
                        <TextField
                          fullWidth
                          type="search"
                          name="q"
                          value={input}
                          onChange={(e) => setInput(e.target.value)}
                          placeholder="0"
                          autoComplete="off"
                        />
                        <Typography variant="body2" sx={{ mx: 2 }}>
                          POLY |
                        </Typography>
                        <Link
                          component="button"
                          sx={{
                            fontSize: "0.875rem",
                            color: "#1976d2",
                            textDecoration: "underline",
                            cursor: "pointer",
                            ml: 1,
                          }}
                        >
                          Max
                        </Link>
                      </Box>
                    </CardContent>
                    <CardActions>
                      <Button
                        fullWidth
                        variant="contained"
                        color="secondary"
                        onClick={handleTrade}
                        disabled={button !== "Trade"}
                      >
                        {button}
                      </Button>
                    </CardActions>
                  </Card>
                </Grid>
              </Grid>

              <Box
                sx={{
                  py: 3,
                  px: 2,
                  border: "1px solid #e0e0e0",
                  borderRadius: 2,
                  backgroundColor: "#f5f5f5",
                }}
              >
                <Typography
                  variant="subtitle1"
                  sx={{ fontWeight: "bold", mb: 1 }}
                  color={"primary"}
                >
                  Description
                </Typography>
                <Typography sx={{ mb: 2 }} color={"primary.contrastText"}>
                  {market?.description}
                </Typography>

                <Box sx={{ borderTop: "1px solid #e0e0e0", pt: 1, mt: 1 }}>
                  <Typography
                    variant="body1"
                    sx={{ fontWeight: "bold" }}
                    color={"primary.contrastText"}
                  >
                    Resolution Source:
                  </Typography>
                  <Link
                    href={market?.resolverUrl}
                    underline="hover"
                    sx={{ color: "brown" }}
                  >
                    {market?.resolverUrl}
                  </Link>
                </Box>
              </Box>
            </Box>
          </Box>
        )}
      </Container>
    </div>
  );
};

export default Details;
